" Basic configuration
set ruler number
set nocp
set tabstop=4 shiftwidth=4 softtabstop=4 noexpandtab
set smarttab autoindent
set incsearch
set smartcase
set hidden


" No bells, flashing windows
set noeb vb t_vb=


" Vundle
filetype off " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Bundles below
Bundle 'gmarik/vundle'

Bundle 'kien/ctrlp.vim'
Bundle 'bling/vim-airline'
Bundle 'tpope/vim-pathogen'
Bundle 'tpope/vim-dispatch'
Bundle 'vim-pandoc/vim-pandoc'
Bundle 'derekwyatt/vim-scala'

filetype plugin indent on     " required

"*******
" Pathogen
execute pathogen#infect('~/configs/vim-bundles/{}')

"******
" Ctrlp setting
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

"****
" Colorscheme settings
syntax enable " Syntax highlighting
colorscheme darkblue
set background=dark

"*******
" vim-airline
set laststatus=2  " Keep status line on all the time
let g:airline_theme='tomorrow'

"****
" Mappings for [[, ]] from vim help
map [[ ?{<CR>w99[{
map ][ /}<CR>b99]}
map ]] j0[[%/{<CR>
map [] k$][%?}<CR>

